page loading
indigotech/onboard-gabriel-sanefuji pull request #12
Opened 2021-01-11 19:05 UTC by Sane98

<img width="391" alt="Screen Shot 2021-01-11 at 16 04 08" src="https://user-images.githubusercontent.com/50017848/104226503-aba2dd80-5426-11eb-9db6-54ebf46ba3e4.png">

2021-01-12 11:28 UTC, alanraso requested changes

2021-01-12 11:28 UTC, alanraso commented on Poke/App.tsx
>  const App = (props: any) => {
Aqui seria uma boa tipar essas props. O `react-native-navigation` tem um tipo pra páginas, com o `componentId` já.

2021-01-12 11:28 UTC, alanraso commented on Poke/App.tsx
>    const handleSubmit = (props: any) => {
O componente `App` já tem acesso as props, não precisa passar aqui no handleSubmit, né?

2021-01-12 11:28 UTC, alanraso commented on Poke/App.tsx
> +      setTimeout(() => {
Por que o setTimeout? 🤔

2021-01-12 11:28 UTC, alanraso commented on Poke/App.tsx
> +            {isLoading ? <ActivityIndicator size={'large'} color="#000000"/> :
Quando a prop é uma string, podemos omitir as chaves `{}`:
```suggestion
            {isLoading ? <ActivityIndicator size='large' color='#000000' /> : 
```

É interessante também mantermos o padrão de aspas simples ou duplas em todas as strings. O lint não reclamou disso?

2021-01-12 11:28 UTC, alanraso commented on Poke/App.tsx
> +              <SubmitButton onTap={() => {handleSubmit(props)}} />
Por conta da não necessidade de repassar as props:
```suggestion
              <SubmitButton onTap={handleSubmit} />
```

2021-01-12 13:01 UTC, Sane98 commented on Poke/App.tsx
> +      setTimeout(() => {
Na verdade era mais pra tirar a foto da loading page, eu achei que tivesse tirado, mas devo ter feito depois do commit

2021-01-12 13:34 UTC, Sane98 commented on Poke/App.tsx
> +            {isLoading ? <ActivityIndicator size={'large'} color="#000000"/> :
Na verdade nao haha

2021-01-12 19:13 UTC, alanraso requested changes

2021-01-12 19:13 UTC, alanraso commented on Poke/App.tsx
> +          options: {
Dessa forma ele vai navegar sempre, mesmo se tiver algum erro no Login, não? Como você pode fazer pra saber se o Login retornou com sucesso?

2021-01-13 12:16 UTC, alanraso approved these changes

2021-01-13 13:12 UTC, merged