infinite scroll
indigotech/onboard-gabriel-sanefuji pull request #16
Opened 2021-01-13 19:38 UTC by Sane98

2021-01-13 19:44 UTC, alanraso commented on Poke/src/pages/users.tsx
> +    if (offset + limit > 142) {
De onde vc tirou esse 142?

2021-01-13 20:09 UTC, Sane98 commented on Poke/src/pages/users.tsx
> +    if (offset + limit > 142) {
eu fui ver no graphiql qual era o último haha Não tive outra ideia pra parar as requests quando chegasse ao fim da lista. Tem alguma sugestão?

2021-01-13 20:10 UTC, Sane98 commented on Poke/src/pages/users.tsx
> +    if (offset + limit > 142) {
Tem o hasNextPage, vou mudar essa parte

2021-01-14 12:15 UTC, alanraso commented on Poke/src/pages/users.tsx
> +    if (offset + limit > 142) {
Isso. A é o servidor informar se há mais usuários a serem buscados ou não, ou seja, você trabalhar com as informações de paginação que a própria query te retorna. Até porque esse 142 pode mudar a qualquer momento, tanto pra menos quanto pra mais.

2021-01-15 15:12 UTC, alanraso commented on Poke/src/pages/users.tsx
> +const queryList = async (offset: number, limit: number) => {
Esse retorno aqui poderia estar tipado.

2021-01-15 15:12 UTC, alanraso commented on Poke/src/pages/users.tsx
> +    });
Um map que retorna o próprio item 🤔 
No caso, não precisa. O map é mais criar outra lista com cada elemento transformado.

2021-01-15 18:19 UTC, betopompolo requested changes

2021-01-15 18:19 UTC, betopompolo commented on Poke/src/pages/users.tsx
> +});
eu vi que vc tava usando o <ApolloProvider> em outro PR né? Se sim, ai não precisaria criar um client em toda a tela

2021-01-15 18:19 UTC, betopompolo commented on Poke/src/pages/users.tsx
> +      `,
só uma sugestão: nos projetos, a gente passa as variáveis da query/mutation através do objeto `variables`. algo assim
```ts
client.query({
  query: gql`...`,
  variables: { limit, offset },
}
```
qualquer coisa me dá um toque

2021-01-15 18:19 UTC, betopompolo commented on Poke/src/pages/users.tsx
> +  const [stop, setStop] = useState(false);
qual a diferença dos states `over` e `stop`?

2021-01-15 20:41 UTC, betopompolo approved these changes
👏

2021-01-15 20:48 UTC, merged