add user frontend
indigotech/onboard-gabriel-sanefuji pull request #18
Opened 2021-01-14 07:22 UTC by Sane98

<img width="338" alt="Screen Shot 2021-01-14 at 04 16 23" src="https://user-images.githubusercontent.com/50017848/104557433-05bac300-5620-11eb-837b-1a40f6b5017b.png">
<img width="339" alt="Screen Shot 2021-01-14 at 04 16 35" src="https://user-images.githubusercontent.com/50017848/104557442-07848680-5620-11eb-9b4b-75477a02d933.png">
<img width="353" alt="Screen Shot 2021-01-14 at 04 15 54" src="https://user-images.githubusercontent.com/50017848/104557448-094e4a00-5620-11eb-9c04-a0785548080f.png">
<img width="356" alt="Screen Shot 2021-01-14 at 04 16 09" src="https://user-images.githubusercontent.com/50017848/104557455-0bb0a400-5620-11eb-98a3-64d883ac4014.png">

2021-01-14 11:41 UTC, betopompolo requested changes

2021-01-14 11:41 UTC, betopompolo commented on Poke/src/components/inputs.tsx
> +};
boa!
agora, vc viu que a diferença entre o `Input` e o `PasswordInput` é só a props `secureTextEntry`? talvez, vc poderia até juntar os dois e ter uma props, no `Input`, chamada `isPassword`, por exemplo. O que acha?

2021-01-14 11:41 UTC, betopompolo commented on Poke/src/components/submit-button.tsx
> +      <Button title={props.text} onPress={props.onTap} />
👏

2021-01-14 11:41 UTC, betopompolo commented on Poke/src/pages/users.tsx
> +            },
esses `options` é bom que a própria página `Add User` configure eles. Dá pra fazer isso usando o Navigation.mergeOptions

2021-01-14 11:41 UTC, betopompolo commented on Poke/src/validation.ts
> +}
hmm esse switch/case daria pra separar em validators mais... concisos, sabe? Algo assim:
```ts
const requiredFieldValidator = (value: string, errorMsg: string) => value === '' ? errorMsg : null;
const emailValidator = (value: string, errorMsg: string) => !email.match(/.+(@{1}.+(.com{1}$|.com.br{1}$))/) ? errorMsg : null;
// ...
```

2021-01-14 12:38 UTC, alanraso commented on Poke/App.tsx
> +                <SubmitButton text={'Entrar'} onTap={handleSubmit} />
Props que são strings dá pra omitir as chaves:
```suggestion
                <Input name='E-mail' text={email} onTextChange={setEmail} />
                <PasswordInput name='' text={password} onTextChange={setPassword} />
                <SubmitButton text='Entrar' onTap={handleSubmit} />
```

2021-01-14 12:38 UTC, alanraso commented on Poke/src/components/inputs.tsx
> +
Acho que pode remover, né?

2021-01-14 12:38 UTC, alanraso commented on Poke/src/pages/add-user.tsx
> +  return (
Aqui talvez melhore a legibilidade desse arquivo se você pular uma linha a cada "troca de context". Por exemplo após a última declaração de state (phone), e antes do return.

2021-01-14 12:38 UTC, alanraso commented on Poke/src/pages/add-user.tsx
> +          </View>
Acho que esse fragment vazio não precisa né? (O <>)

2021-01-14 12:38 UTC, alanraso commented on Poke/src/pages/users.tsx
> +            },
Ou até setando direto lá no arquivo da página: 

```ts
AddUser.options = {
  topBar: {
    title: {
      text: 'Add User',
    },
  },
};
```

Acho á pode tirar os comentários tbm, né?

2021-01-14 12:38 UTC, alanraso commented on Poke/src/pages/add-user.tsx
> +export default AddUser;
A gente costma evitar o export default porque isso abre margem para que quem exporte possa renomear a vontade o componente. A ideia é nós nomearmos todos com nomes claros, mantermos esses nomes e exportamos dessa forma.

```ts
export const AddUser
```

2021-01-14 12:38 UTC, alanraso commented on Poke/src/pages/add-user.tsx
> +const AddUser = () => {
É bom termos o hábito de tipar o que não é trivial para o Typescript:

```suggestion
const AddUser: NavigationPage<Props> = () => {
```

Não lembro de cabeça se é `NavigationPage` mesmo, mas o `react-native-navigation` tem um tipo pra páginas. E as Props, caso não tenha nenhuma customizada, pode ser `{}`

2021-01-14 12:38 UTC, alanraso commented on Poke/src/validation.ts
> +}
Isso é uma de vc reaproveita não só os componentes React, mas também esses validadores. Você deve ter percebido que o campo de e-mail por exmeplo, tem a mesma validação aqui e na tela de login (?)

2021-01-15 13:19 UTC, alanraso approved these changes

2021-01-15 13:19 UTC, alanraso commented on Poke/src/pages/users.tsx
> +        }}>
Esse tipo de callback que ocupa mais de uma linha a gente costuma extrair, com o intuito de deixar essa parte JSX o mais limpa possível em termos de componentes React. Algo nesse sentido:

```ts
const handlePress = () => {
  Navigation.push(props.componentId, {
    component: { name: 'Add User' },
  });
}

// Parte JSX
<TouchableOpacity
    style={styles.button}
    onPress={handlePress}>
```

2021-01-15 21:03 UTC, merged